name: generic_vector_tools
description: A set of tools for using generic vectors
version: 1.0.1
author: Ben Sheron <benmosheron@gmail.com>
homepage: https://github.com/benmosheron/DartDev_Vector.git

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
